apiVersion: extensions/v1beta1
# because of current client
#apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: ${project.artifactId}
    app.kubernetes.io/version: "${project.version}"
  name: ${project.artifactId}
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: ${project.artifactId}
    servicePort: 8080
  rules:
  - host: ${project.artifactId}.test # ATTENTION : project.name has a dash '-'
    http:
      paths:
      - path: /
        backend:
          serviceName: ${project.artifactId}
          servicePort: 8080